--- #YAML:1.0
name: Template-Plugin-EnvHash
version: 1.03
author:
  - Sagar R. Shah
abstract: Environment Variable Hash for TT2
license: perl
requires:
  Template: 0
  Test::More: 0
provides:
  Template::Plugin::EnvHash:
    file: lib/Template/Plugin/EnvHash.pm
    version: 1.03
generated_by: Module::Build version 0.25
