---
name: Template-Plugin-EnvHash
version: 1.04
author: []
abstract: Environment Variable Hash for TT2
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Template: 0
  Test::More: 0
provides:
  Template::Plugin::EnvHash:
    file: lib/Template/Plugin/EnvHash.pm
    version: 1.04
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
